<?php

use Illuminate\Database\Seeder;

class ThemesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('themes')->delete();
        
        \DB::table('themes')->insert(array (
            0 => 
            array (
                'id' => 1,
                'team_id' => 1,
                'creator_id' => 1,
                'name' => 'Black & White',
                'description' => NULL,
                'font_color' => '#000000',
                'font_color_secondary' => '#333333',
                'cta_font_color' => '#000000',
                'cta_bg_color' => 'transparent',
                'background_color' => '#FFFFFF',
                'created_at' => '2016-04-21 09:05:44',
                'updated_at' => '2016-04-21 09:05:44',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 3,
                'team_id' => 3,
                'creator_id' => 1,
                'name' => 'Black & White',
                'description' => NULL,
                'font_color' => '#000000',
                'font_color_secondary' => '#333333',
                'cta_font_color' => '#000000',
                'cta_bg_color' => 'transparent',
                'background_color' => '#FFFFFF',
                'created_at' => '2016-04-21 09:05:44',
                'updated_at' => '2016-04-21 09:05:44',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 4,
                'team_id' => 3,
                'creator_id' => 1,
                'name' => 'Orange & Beige',
                'description' => NULL,
                'font_color' => '#F96302',
                'font_color_secondary' => '#000000',
                'cta_font_color' => '#F96302',
                'cta_bg_color' => 'transparent',
                'background_color' => '#FFF4ED',
                'created_at' => '2016-04-21 09:05:44',
                'updated_at' => '2016-04-21 09:05:44',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 5,
                'team_id' => 3,
                'creator_id' => 1,
                'name' => 'Black & Goldenrod',
                'description' => NULL,
                'font_color' => '#000000',
                'font_color_secondary' => '#000000',
                'cta_font_color' => '#000000',
                'cta_bg_color' => 'transparent',
                'background_color' => '#FFC20E',
                'created_at' => '2016-04-21 09:05:44',
                'updated_at' => '2016-04-21 09:05:44',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 6,
                'team_id' => 3,
                'creator_id' => 1,
                'name' => 'White & Orange',
                'description' => NULL,
                'font_color' => '#FFFFFF',
                'font_color_secondary' => '#FFFFFF',
                'cta_font_color' => '#FFFFFF',
                'cta_bg_color' => 'transparent',
                'background_color' => '#F96302',
                'created_at' => '2016-04-21 09:05:44',
                'updated_at' => '2016-04-21 09:05:44',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 7,
                'team_id' => 3,
                'creator_id' => 1,
                'name' => 'Red & White',
                'description' => NULL,
                'font_color' => '#FFFFFF',
                'font_color_secondary' => '#FFFFFF',
                'cta_font_color' => '#FFFFFF',
                'cta_bg_color' => 'transparent',
                'background_color' => '#b42c31',
                'created_at' => '2016-04-21 09:05:44',
                'updated_at' => '2016-06-02 19:09:56',
                'deleted_at' => '2016-06-02 19:09:56',
            ),
            6 => 
            array (
                'id' => 10,
                'team_id' => 2,
                'creator_id' => 1,
                'name' => 'Yosemite',
                'description' => NULL,
                'font_color' => '#2A3E41',
                'font_color_secondary' => '#79A595',
                'cta_font_color' => '#F0F1D8',
                'cta_bg_color' => 'transparent',
                'background_color' => '#BE8D5C',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '2016-05-05 20:09:35',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 11,
                'team_id' => 2,
                'creator_id' => 1,
                'name' => 'Champions',
                'description' => NULL,
                'font_color' => '#BEB37C',
                'font_color_secondary' => '#CDC092',
                'cta_font_color' => '#BEB37C',
                'cta_bg_color' => 'transparent',
                'background_color' => '#540115',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 12,
                'team_id' => 2,
                'creator_id' => 1,
                'name' => 'Carter\'s',
                'description' => NULL,
                'font_color' => '#ffffff',
                'font_color_secondary' => '#ffffff',
                'cta_font_color' => '#ffffff',
                'cta_bg_color' => 'transparent',
                'background_color' => '#3bc7e7',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '2016-06-21 21:42:12',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 13,
                'team_id' => 2,
                'creator_id' => 1,
                'name' => 'Firenze',
                'description' => NULL,
                'font_color' => '#FFF0A5',
                'font_color_secondary' => '#FFB03B',
                'cta_font_color' => '#FFF0A5',
                'cta_bg_color' => 'transparent',
                'background_color' => '#468966',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 14,
                'team_id' => 2,
                'creator_id' => 1,
                'name' => 'Warhol',
                'description' => NULL,
                'font_color' => '#FEB798',
                'font_color_secondary' => '#FEB798',
                'cta_font_color' => '#DCDD26',
                'cta_bg_color' => 'transparent',
                'background_color' => '#FB2057',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '2016-05-05 20:22:11',
                'deleted_at' => '2016-05-05 20:22:11',
            ),
            11 => 
            array (
                'id' => 15,
                'team_id' => 3,
                'creator_id' => 1,
                'name' => 'Red, White & Blue 2016',
                'description' => NULL,
                'font_color' => '#FFFFFF',
                'font_color_secondary' => '#FFFFFF',
                'cta_font_color' => '#FFFFFF',
                'cta_bg_color' => 'transparent',
                'background_color' => '#df1718',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 16,
                'team_id' => 3,
                'creator_id' => 1,
                'name' => 'Labor Day 2016',
                'description' => NULL,
                'font_color' => '#FFFFFF',
                'font_color_secondary' => '#FFFFFF',
                'cta_font_color' => '#FFFFFF',
                'cta_bg_color' => 'transparent',
                'background_color' => '#d12229',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 17,
                'team_id' => 3,
                'creator_id' => 1,
                'name' => 'Holiday 2016',
                'description' => NULL,
                'font_color' => '#FFFFFF',
                'font_color_secondary' => '#FFFFFF',
                'cta_font_color' => '#FFFFFF',
                'cta_bg_color' => 'transparent',
                'background_color' => '#cc2030',
                'created_at' => '0000-00-00 00:00:00',
                'updated_at' => '0000-00-00 00:00:00',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 18,
                'team_id' => 3,
                'creator_id' => 1,
                'name' => 'SMARTER HOME - Conserve',
                'description' => NULL,
                'font_color' => '#ffffff',
                'font_color_secondary' => '#ffffff',
                'cta_font_color' => '#ffffff',
                'cta_bg_color' => 'transparent',
                'background_color' => '#136436',
                'created_at' => '2016-07-22 18:11:23',
                'updated_at' => '2016-07-22 18:11:23',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 19,
                'team_id' => 3,
                'creator_id' => 1,
                'name' => 'SMARTER HOME - Protect',
                'description' => NULL,
                'font_color' => '#ffffff',
                'font_color_secondary' => '#ffffff',
                'cta_font_color' => '#ffffff',
                'cta_bg_color' => 'transparent',
                'background_color' => '#f96302',
                'created_at' => '2016-07-22 18:12:06',
                'updated_at' => '2016-07-22 18:12:06',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 20,
                'team_id' => 3,
                'creator_id' => 1,
                'name' => 'SMARTER HOME - Enjoy',
                'description' => NULL,
                'font_color' => '#ffffff',
                'font_color_secondary' => '#ffffff',
                'cta_font_color' => '#ffffff',
                'cta_bg_color' => 'transparent',
                'background_color' => '#424d91',
                'created_at' => '2016-07-22 18:12:41',
                'updated_at' => '2016-07-22 18:12:41',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 21,
                'team_id' => 4,
                'creator_id' => 1,
                'name' => 'White & grey',
                'description' => NULL,
                'font_color' => '#585858',
                'font_color_secondary' => '#585858',
                'cta_font_color' => '#585858',
                'cta_bg_color' => 'transparent',
                'background_color' => '#ffffff',
                'created_at' => '2016-10-24 19:33:09',
                'updated_at' => '2016-10-24 19:34:35',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 22,
                'team_id' => 1,
                'creator_id' => 6,
                'name' => 'Oregon Ducks',
                'description' => '',
                'font_color' => '#FEE123',
                'font_color_secondary' => '#FEE123',
                'cta_font_color' => '#FEE123',
                'cta_bg_color' => 'transparent',
                'background_color' => '#154733',
                'created_at' => '2016-11-23 00:54:25',
                'updated_at' => '2016-11-23 00:54:25',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 23,
                'team_id' => 4,
                'creator_id' => 2,
                'name' => 'Yosemite',
                'description' => NULL,
                'font_color' => '#2A3E41',
                'font_color_secondary' => '#79A595',
                'cta_font_color' => '#F0F1D8',
                'cta_bg_color' => 'transparent',
                'background_color' => '#BE8D5C',
                'created_at' => '2016-12-20 21:09:35',
                'updated_at' => '2016-12-20 21:09:35',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 24,
                'team_id' => 4,
                'creator_id' => 2,
                'name' => 'Champions',
                'description' => NULL,
                'font_color' => '#BEB37C',
                'font_color_secondary' => '#CDC092',
                'cta_font_color' => '#BEB37C',
                'cta_bg_color' => 'transparent',
                'background_color' => '#540115',
                'created_at' => '2016-12-20 21:09:35',
                'updated_at' => '2016-12-20 21:09:35',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 25,
                'team_id' => 4,
                'creator_id' => 2,
                'name' => 'Carter\'s',
                'description' => NULL,
                'font_color' => '#ffffff',
                'font_color_secondary' => '#ffffff',
                'cta_font_color' => '#ffffff',
                'cta_bg_color' => 'transparent',
                'background_color' => '#3bc7e7',
                'created_at' => '2016-12-20 21:09:35',
                'updated_at' => '2016-06-21 21:42:12',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 26,
                'team_id' => 4,
                'creator_id' => 2,
                'name' => 'Firenze',
                'description' => NULL,
                'font_color' => '#FFF0A5',
                'font_color_secondary' => '#FFB03B',
                'cta_font_color' => '#FFF0A5',
                'cta_bg_color' => 'transparent',
                'background_color' => '#468966',
                'created_at' => '2016-12-20 21:09:35',
                'updated_at' => '2016-12-20 21:09:35',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 27,
                'team_id' => 1,
                'creator_id' => 6,
                'name' => 'Washington Huskies',
                'description' => '',
                'font_color' => '#e8e3d3',
                'font_color_secondary' => '#e8e3d3',
                'cta_font_color' => '#e8e3d3',
                'cta_bg_color' => 'transparent',
                'background_color' => '#4b2e83',
                'created_at' => '2017-05-12 20:26:09',
                'updated_at' => '2017-05-12 20:26:09',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 28,
                'team_id' => 1,
                'creator_id' => 6,
                'name' => 'Oregon State Beavers',
                'description' => '',
                'font_color' => '#DC4405',
                'font_color_secondary' => '#DC4405',
                'cta_font_color' => '#DC4405',
                'cta_bg_color' => 'transparent',
                'background_color' => '#000000',
                'created_at' => '2017-05-12 20:27:05',
                'updated_at' => '2017-05-12 20:27:05',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 29,
                'team_id' => 1,
                'creator_id' => 6,
                'name' => 'Stanford Cardinal',
                'description' => '',
                'font_color' => '#D2C295',
                'font_color_secondary' => '#D2C295',
                'cta_font_color' => '#D2C295',
                'cta_bg_color' => 'transparent',
                'background_color' => '#8C1515',
                'created_at' => '2017-05-12 20:29:18',
                'updated_at' => '2017-05-12 20:29:18',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}
