version: '2'
services:
  app:
    build:
      context: ./
      dockerfile: docker/local/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  web:
    build:
      context: ./
      dockerfile: docker/local/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - app
    ports:
      - 8080:80
  ngrok:
    container_name: ngrok
    ports:
      - "0.0.0.0:4040:4040"
    image: wernight/ngrok
    links:
      ["web"]
    environment:
      - NGROK_AUTH=3SBM8HGcPJ7cbdC8nXXvh_3TKCoNfqohp9X3AhiLzed
      - NGROK_SUBDOMAIN=vacoda
      - NGROK_PORT=web:80
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "33061:3306"
  redis:
    build:
      context: ./
      dockerfile: docker/local/redis.dockerfile
    volumes:
      - ./storage/redis:/data
    ports:
      - "6379:6379"
  chrome:
    image: robcherry/docker-chromedriver
    environment:
       CHROMEDRIVER_WHITELISTED_IPS: ""
       CHROMEDRIVER_PORT: "9515"
    ports:
       - 9515:9515
    cap_add:
       - "SYS_ADMIN"
volumes:
  data:
  dbdata:
